development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: sephora_development
  pool: 5
  username: rails_psql
  password: r41lspsql
  template: template0

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: sephora_test
  pool: 5
  username: rails_psql
  password: r41lspsql
  template: template0
