development:
	mysql41: 9312
  configuration_file: Rails.root+"/config/development.sphinx.conf"
  log: Rails.root+"/log/searchd.log"
  query_log: Rails.root+"/log/searchd.query.log"
  pid_file: Rails.root+"/log/searchd.development.pid"
  #mem_limit: 128M